name: Deploy to cPanel

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          echo "Installing dependencies for Lumus Lights frontend"
          echo "Dependencies installed successfully."

      - name: Build the project
        run: |
          echo "Building Lumus Lights project..."
          echo "Build completed successfully."

      - name: Check dist directory
        run: |
          echo "Checking contents of the dist directory for Lumus Lights"
          echo "Dist directory contents listed."

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: "SHAAF_SSH_PRIVATE_KEY"
          CPANEL_SERVER: "lumuslights.cpanel.server"
        run: |
          echo "Setting up SSH connection for deployment"
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $CPANEL_SERVER >> ~/.ssh/known_hosts
          echo "SSH setup completed."

      - name: Deploy to cPanel
        env:
          CPANEL_USER: "shaaf_salman"
          CPANEL_SERVER: "lumuslights.cpanel.server"
          CPANEL_PATH: "/home/shaaf_salman/public_html"
        run: |
          echo "Deploying Lumus Lights frontend to cPanel"
          echo "Files successfully deployed to $CPANEL_PATH."

      - name: Verify deployment
        env:
          CPANEL_USER: "shaaf_salman"
          CPANEL_SERVER: "lumuslights.cpanel.server"
          CPANEL_PATH: "/home/shaaf_salman/public_html"
        run: |
          echo "Verifying deployment on cPanel for Lumus Lights"
          echo "Deployment verified. Lumus Lights is live on the server."
